//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spareio.UI.SpareioClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SpareioClient.ISpareioWCF")]
    public interface ISpareioWCF {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/ISpareioWCF/RunProcess", ReplyAction="http://tempuri.org/ISpareioWCF/RunProcessResponse")]
        int RunProcess(string fullPath, string args);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpareioWCFChannel : Spareio.UI.SpareioClient.ISpareioWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpareioWCFClient : System.ServiceModel.ClientBase<Spareio.UI.SpareioClient.ISpareioWCF>, Spareio.UI.SpareioClient.ISpareioWCF {
        
        public SpareioWCFClient() {
        }
        
        public SpareioWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpareioWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpareioWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpareioWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RunProcess(string fullPath, string args) {
            return base.Channel.RunProcess(fullPath, args);
        }
    }
}
